# Generated by Django 3.2.7 on 2021-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='a@test.localhost', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='unkonwn', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='unkonw', max_length=20),
            preserve_default=False,
        ),
    ]
