# Generated by Django 3.2.7 on 2021-10-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_datetime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
