# Generated by Django 3.2.7 on 2021-10-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20211021_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='posts_images'),
        ),
    ]
